import { createFileRoute } from '@tanstack/react-router'
import { Bot, CirclePause, Play, Plus, Search, TerminalSquare } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'

export const Route = createFileRoute('/app/bots')({ component: BotsPage })

function BotsPage() {
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="font-serif text-4xl font-medium tracking-tight">Bots</h1><p className="mt-2 text-sm text-muted-foreground">Manage deployments, runtime health, and logs.</p></div><Button><Plus className="size-4" /> Deploy bot</Button></div><div className="flex gap-3"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search bots" /></div></div><div className="grid gap-4 lg:grid-cols-2">{['Support Concierge', 'Daily Digest', 'Onboarding Guide'].map((name, i) => <Card key={name} className="border-border/70"><CardHeader className="flex flex-row items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-primary/10 p-2.5 text-primary"><Bot className="size-5" /></div><div><CardTitle className="text-base">{name}</CardTitle><p className="text-xs text-muted-foreground">@northstar_{i === 0 ? 'support' : i === 1 ? 'digest' : 'start'}</p></div></div><span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-semibold text-emerald-700">Running</span></CardHeader><CardContent><div className="grid grid-cols-3 gap-3 border-y border-border/60 py-4 text-xs"><div><p className="text-muted-foreground">Uptime</p><p className="mt-1 font-semibold">14d 06h</p></div><div><p className="text-muted-foreground">Memory</p><p className="mt-1 font-semibold">128 MB</p></div><div><p className="text-muted-foreground">Version</p><p className="mt-1 font-semibold">v1.8.2</p></div></div><div className="mt-4 flex justify-between"><Button variant="ghost" size="sm"><TerminalSquare className="size-4" /> View logs</Button><Button variant="outline" size="sm">{i === 2 ? <Play className="size-4" /> : <CirclePause className="size-4" />} {i === 2 ? 'Start' : 'Pause'}</Button></div></CardContent></Card>)}</div></div>
}
